name: Swift

on:
  push:
    branches: [ develop, feature/*, main ]
  pull_request:
    branches: [ develop ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        xcodebuild test -workspace 'CatchMe.xcodeproj' -scheme 'CatchMeTests' -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
 
