name: Swift

on:
  push:
    branches: [ develop, feature/*, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: 
        pod install --repo-update --clean-install --project-directory=CatchMe/
        xcodebuild test -workspace CatchMe.xcworkspace -scheme CatchMe -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
