name: Swift

on:
  push:
    branches: [ develop, feature/*, main ]
  pull_request:
    branches: [ develop ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.4
 
