name: Swift

on:
  push:
    branches: [ develop, feature/*, main ]
  pull_request:
    branches: [ develop ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: List Simulators
      run: xcrun instruments -s
    - name: Run tests
      run: xcodebuild clean test -workspace 'CatchMe.xcworkspace' -scheme 'CatchMe' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
