name: Swift

on:
  push:
    branches: [ develop, feature/*, main ]
  pull_request:
    branches: [ develop ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -workspace 'CatchMe.xcworkspace' -scheme 'CatchMe' -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
    - name: Run tests
      run: xcodebuild test -workspace 'CatchMe.xcworkspace' -scheme 'CatchMe' -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4'
