name: Swift

on:
  push:
    branches: [ develop, feature/*, main ]
  pull_request:
    branches: [ develop ]
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        pod install --repo-update --clean-install --project-directory=CatchMe/
        xcodebuild test -workspace './CatchMe/CatchMe.xcworkspace' -scheme 'CatchMeTests' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest'
 
